[template]
cargo_generate_version = ">=0.23.0"

[hooks]
pre = [
    "prehook_license.rhai",
]

[placeholders.rust-version]
prompt = "What is the minimum rust version for the project?"
type = "string"
default = "1.90.0"

[placeholders.toplevel_crate]
prompt = "Please select the crate type"
type = "string"
choices = [
    "bin",
    "lib",
    "bin-and-lib",
]
default = "bin-and-lib"

[conditional.'toplevel_crate == "bin"']
ignore = ["src/lib.rs"]

[conditional.'toplevel_crate == "lib"']
ignore = ["src/main.rs"]
